name: Get Citation Data

on:
  page_build:
  schedule:
    - cron: "0 8 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Reqs
        run: |
          sudo apt-get install python3-setuptools
      - name: Run
        run: |
          cd ./google_scholar_crawler
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
          python main.py
          cd ./results
          git init
          git config --local user.name "${GITHUB_ACTOR}"
          git config --local user.email shenmishajing@gmail.com
          export remote_repo="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
          git add *.json
          git commit -m "Updated Citation Data"
          git push "${remote_repo}" HEAD:google-scholar-stats --force
        env:
          GOOGLE_SCHOLAR_ID: ${{ secrets.GOOGLE_SCHOLAR_ID }}
